#key=value pair
# : colon also accepted
# the above are separator
# property file is file from java.util


registrationFormUrl=https://vinothqaacademy.com/demo-site/
healthCareUrl=https://vinothqaacademy.com/demo-page-healthcare/
multiplewindow=https://vinothqaacademy.com/multiple-windows/
handledropdowns=https://vinothqaacademy.com/drop-down/
handleframes=https://vinothqaacademy.com/iframe/



 
 